### ISSUE TITLE
Can not change configure to Mysql DB 

### ISSUE THREAD

**Issue by anhtata** [fabriciomrtnz/FNHMVC#3]
I change configure functional to MySQL DB but can not 
Code: 
           return  Fluently.Configure()
                .Database(MySqlConfiguration.Standard.ConnectionString(c => c.FromConnectionStringWithKey("ConnString")))
                .Mappings(m => m.FluentMappings.AddFromAssemblyOf<CategoryMap>());

I newbie to use FNHMVC I got error CS0103: The name 'MySqlConfiguration' does not exist in the current context

Please help!

**Comment by anhtata** [comment]
It okie now, My typo mistakes should be:

return  Fluently.Configure()
                .Database(MySQLConfiguration.Standard.ConnectionString(c => c.FromConnectionStringWithKey("ConnString")))
                .Mappings(m => m.FluentMappings.AddFromAssemblyOf<CategoryMap>());

**Comment by anhtata** [comment]
I got typo mistakes, It should be 
return  Fluently.Configure()
                .Database(MySQLConfiguration.Standard.ConnectionString(c => c.FromConnectionStringWithKey("ConnString")))
                .Mappings(m => m.FluentMappings.AddFromAssemblyOf<CategoryMap>());

**Comment by fabriciomrtnz** [comment]
I'm glad you saved it. In any case you can check out nhibertante docs for updated info on connecting to MySQL.
