### ISSUE TITLE
Error when Fluent NHibernate mapping

### ISSUE THREAD

**Issue by anhtata** [fabriciomrtnz/FNHMVC#4]
Dear!
I got a message at runtime when system load 

return  Fluently.Configure()
                .Database(MySQLConfiguration.Standard.ConnectionString(c => c.FromConnectionStringWithKey(ConnString)))
                .Mappings(m => m.FluentMappings.AddFromAssemblyOf<CategoryMap>())
                .Mappings(m => m.FluentMappings.AddFromAssemblyOf<UserMap>());

A first chance exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'NHibernate.XmlSerializers, Version=3.3.1.4000, Culture=neutral, PublicKeyToken=aa95f207798dfdb4' or one of its dependencies. The system cannot find the file specified.

Please help me!

**Comment by fabriciomrtnz** [comment]
Hi,

Sorry been busy on other projects. Seems to me the error is related to the nhibernate try removing and adding the package.
