### ISSUE TITLE
How to get the ID of recently saved

### ISSUE THREAD

**Issue by irrahub** [fabriciomrtnz/FNHMVC#5]
Hi, 

I enabled to save the command object. But I couldn't get ID value after saved the command. 

`IEnumerable<ValidationResult> error = commandBus.Validate(command);
                ModelState.AddModelErrors(error);
                if (ModelState.IsValid)
                {
                    var result = commandBus.Submit(command);`

I would like to get the ID from the command  object. How can I change the code in which part. 

Thanks
Win

**Comment by fabriciomrtnz** [comment]
If NHibernate is configured correctly with the corresponding SQL server you should be able to get the id directly from the command object right after the submit function.
